[package]
name = "syl"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.106.0"
cranelift-module = "0.106.0"
cranelift-object = "0.106.0"
cranelift-frontend = "0.106.0"
cranelift-native = "0.106.0"

[[bin]]
name = "syl"
path = "src/main.rs"

[[bin]]
name = "syl_setup"
path = "src/setup.rs"
